# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1080)
        MainWindow.setStyleSheet("QWidget#centralwidget{\n"
"border-image: url(:/newPrefix/a.png);\n"
"border:1px solid #161A1E;   /*边框的粗细，颜色*/\n"
"border-radius:40px;    /*设置圆角半径 */\n"
"padding:2px 4px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(530, 30, 1241, 141))
        font = QtGui.QFont()
        font.setFamily("KacstOne")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(82, 129, 162, 255);\n"
"")
        self.label.setObjectName("label")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 380, 1080))
        self.frame.setStyleSheet("#frame{\n"
"background-color: qlineargradient(spread:pad, x1:0.49, y1:0.00640909, x2:0.526, y2:1, stop:0 rgba(82, 129, 162, 255), stop:1 rgba(177, 116, 213, 247));\n"
"border-radius : 40 ;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(80, 350, 220, 80))
        font = QtGui.QFont()
        font.setFamily("KacstArt")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 0, 0, 60), stop:1 rgba(0, 0, 0, 57));\n"
"border-radius : 40 ;\n"
"color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));")
        self.pushButton.setObjectName("pushButton")
        self.detectButton = QtWidgets.QPushButton(self.frame)
        self.detectButton.setGeometry(QtCore.QRect(80, 650, 220, 80))
        font = QtGui.QFont()
        font.setFamily("KacstArt")
        font.setPointSize(20)
        self.detectButton.setFont(font)
        self.detectButton.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 0, 0, 60), stop:1 rgba(0, 0, 0, 57));\n"
"border-radius : 40 ;\n"
"color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));")
        self.detectButton.setObjectName("detectButton")
        self.openButton = QtWidgets.QPushButton(self.frame)
        self.openButton.setGeometry(QtCore.QRect(80, 200, 220, 80))
        font = QtGui.QFont()
        font.setFamily("KacstArt")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.openButton.setFont(font)
        self.openButton.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 0, 0, 60), stop:1 rgba(0, 0, 0, 57));\n"
"border-radius : 40 ;\n"
"color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));")
        self.openButton.setObjectName("openButton")
        self.imageButton = QtWidgets.QPushButton(self.frame)
        self.imageButton.setGeometry(QtCore.QRect(80, 500, 220, 80))
        font = QtGui.QFont()
        font.setFamily("KacstArt")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.imageButton.setFont(font)
        self.imageButton.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 0, 0, 60), stop:1 rgba(0, 0, 0, 57));\n"
"border-radius : 40 ;\n"
"color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));")
        self.imageButton.setObjectName("imageButton")
        self.exportButton = QtWidgets.QPushButton(self.frame)
        self.exportButton.setGeometry(QtCore.QRect(80, 850, 220, 80))
        font = QtGui.QFont()
        font.setFamily("KacstArt")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.exportButton.setFont(font)
        self.exportButton.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 0, 0, 60), stop:1 rgba(0, 0, 0, 57));\n"
"border-radius : 40 ;\n"
"color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));")
        self.exportButton.setObjectName("exportButton")
        self.escButton = QtWidgets.QPushButton(self.frame)
        self.escButton.setGeometry(QtCore.QRect(20, 20, 31, 31))
        self.escButton.setStyleSheet("background-color: rgb(204, 72, 72);\n"
"border-radius : 15 ;\n"
"color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));")
        self.escButton.setText("")
        self.escButton.setObjectName("escButton")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(1180, 170, 680, 520))
        self.frame_3.setStyleSheet("#frame_3{\n"
"background-color: qlineargradient(spread:pad, x1:0.505526, y1:0.903, x2:0.504263, y2:0.079, stop:0.105263 rgba(255, 177, 82, 113), stop:0.905263 rgba(255, 180, 180, 207));\n"
"border-radius : 80 ;\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.detectlabel = QtWidgets.QLabel(self.frame_3)
        self.detectlabel.setGeometry(QtCore.QRect(20, 20, 640, 480))
        self.detectlabel.setStyleSheet("")
        self.detectlabel.setText("")
        self.detectlabel.setObjectName("detectlabel")
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setGeometry(QtCore.QRect(450, 170, 680, 520))
        self.frame_4.setStyleSheet("#frame_4{\n"
"background-color: qlineargradient(spread:pad, x1:0.505526, y1:0.903, x2:0.504263, y2:0.079, stop:0.105263 rgba(255, 177, 82, 113), stop:0.905263 rgba(255, 180, 180, 207));\n"
"border-radius : 80 ;\n"
"}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.videolabel = QtWidgets.QLabel(self.frame_4)
        self.videolabel.setGeometry(QtCore.QRect(20, 20, 640, 480))
        self.videolabel.setStyleSheet("")
        self.videolabel.setText("")
        self.videolabel.setObjectName("videolabel")
        self.frame_5 = QtWidgets.QFrame(self.centralwidget)
        self.frame_5.setGeometry(QtCore.QRect(450, 729, 1411, 291))
        self.frame_5.setStyleSheet("#frame_5{\n"
"background-color: qlineargradient(spread:pad, x1:0.505526, y1:0.903, x2:0.504263, y2:0.079, stop:0.105263 rgba(255, 177, 82, 113), stop:0.905263 rgba(255, 180, 180, 207));\n"
"border-radius : 80 ;\n"
"}")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.tableWidget = QtWidgets.QTableWidget(self.frame_5)
        self.tableWidget.setGeometry(QtCore.QRect(30, 20, 1351, 251))
        self.tableWidget.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(0, 0, 0, 0));\n"
"")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Character detection system for deep learning"))
        self.pushButton.setText(_translate("MainWindow", "PAUSE"))
        self.detectButton.setText(_translate("MainWindow", "DETETC"))
        self.openButton.setText(_translate("MainWindow", "OPEN"))
        self.imageButton.setText(_translate("MainWindow", "IMAGE"))
        self.exportButton.setText(_translate("MainWindow", "EXPORT"))
import picture_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
